### ISSUE TITLE
fonts issue

### ISSUE THREAD

**Issue by taocp** [tuna/gdanmaku#3]
about `danmaku_ui.py` 138 line:

`cr.select_font_face("WenQuanYi Micro Hei"` leads to Chinese characters into the boxs(汉字显示为方框).

install the `WenQuanYi Micro Hei` font or change code using other font can sovle this problem, 

but maybe there is a better way intead of hardcode fonts ?

`gdanmaku`  detect fonts the user/OS has and select one for drawing?

many thanks. this is an interesting program.

**Comment by bigeagle** [comment]
I plan to add configuration file so that user can choose font.

**Comment by taocp** [comment]
good idea. :+1:

**Comment by bigeagle** [comment]
plase pull the latest version and run

```
./danmaku.py --config
```

**Comment by taocp** [comment]
额，发现有一个奇怪的问题，帮忙看看怎么回事好不好啊，嘿嘿。
我都是`./danmaku_ui.py`这样运行的。
1. 在我这里，`./danmaku_ui.py`中有一行`from config import load_config`，改成`from settings import load_config`就可以运行了。
2. 运行`./danmaku.py --config`后随机选择了一个字体(忘记究竟是哪个了),然后再运行就会出错。
   ![gdan-3](https://cloud.githubusercontent.com/assets/5194281/4781811/26f9c700-5cc1-11e4-80f3-8651f88ad265.png)
   而且还没办法重新配置了，运行`./danmaku.py --config`以后出现的窗口是这样的：
   ![gdan-1](https://cloud.githubusercontent.com/assets/5194281/4781812/5c0091c2-5cc1-11e4-8d1e-1575906f9ba1.png)
   点击字体想要选择时，程序直接关掉了，错误信息：
   ![gdan-2](https://cloud.githubusercontent.com/assets/5194281/4781814/72654ed0-5cc1-11e4-9430-8974ae2d4d37.png)

做一个伸手党很可耻，不过我不懂这些，还是交给专业人士比较好，嘿嘿 :smile: 
辛苦啦！

**Comment by bigeagle** [comment]
oh it's my fault. Pull latest version,  `rm ~/.config/gdanmaku/config.json` and try config again.
If it does not fix, feel free to tell me.

cheers,

**Comment by taocp** [comment]
嗯嗯，基本工作得很好啦。
只有最后一个小问题了，选择的**字体名称**(例如“宋体”而非"WenQuanYi")为中文时，`~/.config/gdanmaku/config.json`内容：
![gdan-4](https://cloud.githubusercontent.com/assets/5194281/4781929/37b2ea80-5ccc-11e4-8e13-e9bd83bec85e.png)
好像有什么奇怪的东西混进去了，如果再次`./danmaku.py --config`会有点问题：
![gdan-5](https://cloud.githubusercontent.com/assets/5194281/4781932/8f0ec146-5ccc-11e4-8d46-ac64fd9520a1.png)

:D

**Comment by bigeagle** [comment]
I see, try the latest version :)

**Comment by taocp** [comment]
awesome!
You just add one letter 'u', 看来我要努力学习，提高自己的水平了。

many thanks!
